server:
  port: 8081

spring:
  application:
    name: secureaid

  config:
    import: optional:aws-secretsmanager:/secureaid/dev/

  datasource:
    url: jdbc:postgresql://localhost:5432/${DBNAME}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

secureaid:
  jwt:
    expiration-ms: 600000 # 1 hour (in milliseconds)


cloud:
  aws:
    region:
      static: ${APPREGION}
      auto: false